In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import statsmodels.api as sm

In [3]:
df = pd.read_csv('C:\\Users\\user\\Downloads\\Automobile (1).csv')
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [4]:
df.shape

(201, 26)

In [5]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
symboling              201 non-null int64
normalized_losses      201 non-null int64
make                   201 non-null object
fuel_type              201 non-null object
aspiration             201 non-null object
number_of_doors        201 non-null object
body_style             201 non-null object
drive_wheels           201 non-null object
engine_location        201 non-null object
wheel_base             201 non-null float64
length                 201 non-null float64
width                  201 non-null float64
height                 201 non-null float64
curb_weight            201 non-null int64
engine_type            201 non-null object
number_of_cylinders    201 non-null object
engine_size            201 non-null int64
fuel_system            201 non-null object
bore                   201 non-null float64
stroke                 201 non-null float64
compression_ratio      201 non-null float64
horsepower             201 non-null int64
peak_rpm               201 non-null int64
city_mpg               201 non-null int64
highway_mpg            201 non-null int64
price                  201 non-null int64
dtypes: float64(7), int64(9), object(10)
memory usage: 40.9+ KB

In [7]:
categorical_cols = df.columns[df.dtypes==object].tolist()

In [8]:
categorical_cols

['make',
 'fuel_type',
 'aspiration',
 'number_of_doors',
 'body_style',
 'drive_wheels',
 'engine_location',
 'engine_type',
 'number_of_cylinders',
 'fuel_system']

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df[categorical_cols] = df[categorical_cols].apply(lambda x : le.fit_transform(x))

In [10]:
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,0,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,0,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,0,1,0,1,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,1,1,0,0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,1,1,0,0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450

In [11]:
df.corr()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
symboling,1.000000,0.474993,-0.129645,0.196735,-0.054615,0.672671,-0.600333,-0.053056,0.212339,-0.535987,...,-0.110581,0.091601,-0.146355,0.018373,-0.182196,0.075287,0.279849,-0.035527,0.036233,-0.082391
normalized_losses,0.474993,1.000000,-0.314394,0.094684,0.017122,0.367762,-0.248984,0.365953,0.010332,0.007815,...,0.174788,0.298960,0.007498,0.062666,-0.120846,0.276665,0.211812,-0.301206,-0.264594,0.208886
make,-0.129645,-0.314394,1.000000,-0.109330,0.071254,-0.159325,0.090621,-0.034844,0.053312,0.073930,...,-0.084770,0.144769,0.239282,-0.213099,0.132554,-0.066678,-0.207617,0.065761,0.059111,-0.163646
fuel_type,0.196735,0.094684,-0.109330,1.000000,-0.408228,0.189755,-0.147654,-0.131096,0.040917,-0.307237,...,-0.070779,0.042824,-0.055670,-0.234575,-0.985231,0.167681,0.476903,-0.265676,-0.198690,-0.110326
aspiration,-0.054615,0.017122,0.071254,-0.408228,1.000000,-0.041431,0.072079,0.094469,-0.057496,0.256889,...,0.110040,0.282269,0.229465,0.209809,0.307522,0.252745,-0.193098,-0.189237,-0.241851,0.179578
number_of_doors,0.672671,0.367762,-0.159325,0.189755,-0.041431,1.000000,-0.683109,0.109664,0.140903,-0.453074,...,-0.031056,0.007463,-0.134536,0.029404,-0.175370,0.101785,0.240077,0.025730,0.044708,-0.048264
body_style,-0.600333,-0.248984,0.090621,-0.147654,0.072079,-0.683109,1.000000,-0.161004,-0.278350,0.407128,...,-0.063692,-0.054810,0.023873,-0.024304,0.134622,-0.138075,-0.101919,0.014217,-0.021328,-0.072933
drive_wheels,-0.053056,0.365953,-0.034844,-0.131096,0.094469,0.109664,-0.161004,1.000000,0.149369,0.467661,...,0.526027,0.435926,0.467181,0.096913,0.120125,0.547854,-0.040380,-0.469240,-0.472893,0.588333
engine_location,0.212339,0.010332,0.053312,0.040917,-0.057496,0.140903,-0.278350,0.149369,1.000000,-0.189115,...,0.199367,0.106735,0.188802,-0.140428,-0.020467,0.342368,0.200322,-0.157132,-0.102964,0.331062
wheel_base,-0.535987,0.007815,0.073930,-0.307237,0.256889,-0.453074,0.407128,0.467661,-0.189115,1.000000,...,0.572027,0.381273,0.495210,0.148239,0.250313,0.372607,-0.362642,-0.470606,-0.543304,0.584642
length,-0.365404,0.103659,0.110468,-0.211187,0.230085,-0.408371,0.347571,0.495197,-0.053086,0.876024,...,0.685025,0.551120,0.610324,0.116745,0.159733,0.577923,-0.281932,-0.665192,-0.698142,0.690628
width,-0.242423,0.153752,-0.005115,-0.244356,0.305732,-0.237340,0.155366,0.481395,-0.052205,0.814507,...,0.729436,0.513371,0.545028,0.186352,0.189867,0.613488,-0.242569,-0.633531,-0.680635,0.751265
height,-0.550160,-0.335476,0.230754,-0.281578,0.090336,-0.550645,0.571107,-0.025096,-0.109225,0.590742,...,0.074694,0.018196,0.186701,-0.086508,0.259737,-0.085544,-0.311922,-0.049800,-0.104812,0.135486
curb_weight,-0.233118,0.178547,0.017115,-0.221046,0.321955,-0.215319,0.145762,0.590642,0.051287,0.782097,...,0.849072,0.602638,0.644871,0.162179,0.156433,0.757762,-0.279027,-0.749543,-0.794889,0.834415
engine_type,0.091801,-0.093657,-0.044549,0.124051,-0.130898,0.107988,-0.080350,-0.067339,0.125683,-0.143928,...,0.118248,-0.042551,0.066696,-0.117249,-0.105280,0.144699,0.056675,-0.171524,-0.156458,0.126025
number_of_cylinders,0.199377,0.144092,-0.049947,0.120638,-0.129771,0.183451,-0.063741,0.231177,0.136009,-0.190489,...,-0.064607,0.028508,-0.029008,0.021088,-0.072699,0.202425,0.251823,-0.157424,-0.101386,0.005509
engine_size,-0.110581,0.174788,-0.084770,-0.070779,0.110040,-0.031056,-0.063692,0.526027,0.199367,0.572027,...,1.000000,0.507264,0.577265,0.184605,0.028889,0.821685,-0.254961,-0.650546,-0.679571,0.872335
fuel_system,0.091601,0.298960,0.144769,0.042824,0.282269,0.007463,-0.054810,0.435926,0.106735,0.381273,...,0.507264,1.000000,0.471751,0.079692,-0.099933,0.669342,0.019096,-0.663651,-0.638017,0.521689
bore,-0.146355,0.007498,0.239282,-0.055670,0.229465,-0.134536,0.023873,0.467181,0.188802,0.495210,...,0.577265,0.471751,1.000000,-0.057887,0.001971,0.563921,-0.269486,-0.576954,-0.586917,0.543052
stroke,0.018373,0.062666,-0.213099,-0.234575,0.209809,0.029404,-0.024304,0.096913,-0.140428,0.148239,...,0.184605,0.079692,-0.057887,1.000000,0.183855,0.092493,-0.019004,-0.053955,-0.051793,0.081434
compression_ratio,-0.182196,-0.120846,0.132554,-0.985231,0.307522,-0.175370,0.134622,0.120125,-0.020467,0.250313,...,0.028889,-0.099933,0.001971,0.183855,1.000000,-0.212984,-0.437263,0.331425,0.268465,0.071107
horsepower,0.075287,0.276665,-0.066678,0.167681,0.252745,0.101785,-0.138075,0.547854,0.342368,0.372607,...,0.821685,0.669342,0.563921,0.092493,-0.212984,1.000000,0.104645,-0.820400,-0.804241,0.810795
peak_rpm,0.279849,0.211812,-0.207617,0.476903,-0.193098,0.240077,-0.101919,-0.040380,0.200322,-0.362642,...,-0.254961,0.019096,-0.269486,-0.019004,-0.437263,0.104645,1.000000,-0.117699,-0.058054,-0.104846
city_mpg,-0.035527,-0.301206,0.065761,-0.265676,-0.189237,0.025730,0.014217,-0.469240,-0.157132,-0.470606,...,-0.650546,-0.663651,-0.576954,-0.053955,0.331425,-0.820400,-0.117699,1.000000,0.972044,-0.686571
highway_mpg,0.036233,-0.264594,0.059111,-0.198690,-0.241851,0.044708,-0.021328,-0.472893,-0.102964,-0.543304,...,-0.679571,-0.638017,-0.586917,-0.051793,0.268465,-0.804241,-0.058054,0.972044,1.000000,-0.704692
price,-0.082391,0.208886,-0.163646,-0.110326,0.179578,-0.048264,-0.072933,0.588333,0.331062,0.584642,...,0.872335,0.521689,0.543052,0.081434,0.071107,0.810795,-0.104846,-0.686571,-0.704692,1.000000

In [12]:
x = df.drop('price',axis=1)
y = df['price']

In [13]:
Xc = sm.add_constant(x)

C:\Users\user\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [14]:
model = sm.OLS(y,Xc).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.894
Model:                            OLS   Adj. R-squared:                  0.878
Method:                 Least Squares   F-statistic:                     58.73
Date:                Thu, 16 Apr 2020   Prob (F-statistic):           7.47e-72
Time:                        21:38:42   Log-Likelihood:                -1864.7
No. Observations:                 201   AIC:                             3781.
Df Residuals:                     175   BIC:                             3867.
Df Model:                          25
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const               -5.878e+04   1.85e+04     -3.183      0.002   -9.52e+04   -2.23e+04
symboling             241.3580    291.215      0.829      0.408    -333.388     816.104
normalized_losses     -10.8108      8.964     -1.206      0.229     -28.503       6.881
make                 -202.5676     39.504     -5.128      0.000    -280.533    -124.602
fuel_type           -2011.5976   6931.012     -0.290      0.772   -1.57e+04    1.17e+04
aspiration            817.5160   1015.563      0.805      0.422   -1186.811    2821.843
number_of_doors      -670.7563    678.948     -0.988      0.325   -2010.737     669.224
body_style           -925.0613    390.453     -2.369      0.019   -1695.664    -154.459
drive_wheels         1233.6069    616.735      2.000      0.047      16.411    2450.803
engine_location      1.128e+04   2215.010      5.091      0.000    6906.033    1.56e+04
wheel_base            115.4375    108.778      1.061      0.290     -99.248     330.122
length                 10.5005     56.932      0.184      0.854    -101.862     122.863
width                 568.4756    272.606      2.085      0.038      30.457    1106.494
height                245.4485    145.801      1.683      0.094     -42.307     533.204
curb_weight             2.4308      1.667      1.458      0.147      -0.860       5.721
engine_type           322.9291    288.503      1.119      0.265    -246.465     892.323
number_of_cylinders   186.9623    425.595      0.439      0.661    -652.997    1026.921
engine_size            92.3722     20.365      4.536      0.000      52.180     132.564
fuel_system            66.6992    161.070      0.414      0.679    -251.190     384.589
bore                -1598.6946   1166.755     -1.370      0.172   -3901.418     704.028
stroke              -2843.2372    799.690     -3.555      0.000   -4421.515   -1264.960
compression_ratio     -40.5919    498.841     -0.081      0.935   -1025.110     943.926
horsepower             13.8531     24.562      0.564      0.573     -34.624      62.330
peak_rpm                1.5628      0.693      2.254      0.025       0.195       2.931
city_mpg              -87.3612    173.317     -0.504      0.615    -429.422     254.700
highway_mpg            93.1929    153.113      0.609      0.544    -208.993     395.379
==============================================================================
Omnibus:                       38.783   Durbin-Watson:                   0.961
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              164.096
Skew:                           0.641   Prob(JB):                     2.33e-36
Kurtosis:                       7.237   Cond. No.                     5.54e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.54e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### BACKWARD ELIMINATION

In [15]:
cols = list(x.columns)
pmax = 1
while (len(cols)>0):
    p=[]
    xc = x[cols]
    xc = sm.add_constant(xc)
    model = sm.OLS(y,xc).fit()
    p = pd.Series(model.pvalues.values[1:],index = cols)
    pmax = max(p)
    feature_with_pmax = p.idxmax()
    if(pmax > 0.05):
        cols.remove(feature_with_pmax)
    else:
        break
selected_features_BE = cols
print(selected_features_BE)

['make', 'body_style', 'drive_wheels', 'engine_location', 'width', 'height', 'curb_weight', 'engine_size', 'stroke', 'peak_rpm']

In [16]:
x_update = x[cols]

In [17]:
x_update.head()

,make,body_style,drive_wheels,engine_location,width,height,curb_weight,engine_size,stroke,peak_rpm
0,0,0,2,0,64.1,48.8,2548,130,2.68,5000
1,0,0,2,0,64.1,48.8,2548,130,2.68,5000
2,0,2,2,0,65.5,52.4,2823,152,3.47,5000
3,1,3,1,0,66.2,54.3,2337,109,3.40,5500
4,1,3,0,0,66.4,54.3,2824,136,3.40,5500

In [18]:
x_update = x_update.drop('make',axis=1)

In [19]:
x_update.head()

,body_style,drive_wheels,engine_location,width,height,curb_weight,engine_size,stroke,peak_rpm
0,0,2,0,64.1,48.8,2548,130,2.68,5000
1,0,2,0,64.1,48.8,2548,130,2.68,5000
2,2,2,0,65.5,52.4,2823,152,3.47,5000
3,3,1,0,66.2,54.3,2337,109,3.40,5500
4,3,0,0,66.4,54.3,2824,136,3.40,5500

In [20]:
x_update.engine_location.value_counts()

0    198
1      3
Name: engine_location, dtype: int64

In [21]:
x_update.body_style.value_counts()

3    94
2    68
4    25
1     8
0     6
Name: body_style, dtype: int64

In [22]:
x_update.drive_wheels.value_counts()

1    118
2     75
0      8
Name: drive_wheels, dtype: int64

In [23]:
x_drive_wheels = pd.get_dummies(x_update.drive_wheels)
x_body_style = pd.get_dummies(x_update.body_style)

In [24]:
x_drive_wheels

     0  1  2
0    0  0  1
1    0  0  1
2    0  0  1
3    0  1  0
4    1  0  0
5    0  1  0
6    0  1  0
7    0  1  0
8    0  1  0
9    0  0  1
10   0  0  1
11   0  0  1
12   0  0  1
13   0  0  1
14   0  0  1
15   0  0  1
16   0  0  1
17   0  1  0
18   0  1  0
19   0  1  0
20   0  1  0
21   0  1  0
22   0  1  0
23   0  1  0
24   0  1  0
25   0  1  0
26   0  1  0
27   0  1  0
28   0  1  0
29   0  1  0
..  .. .. ..
171  0  1  0
172  0  1  0
173  0  1  0
174  0  0  1
175  0  0  1
176  0  0  1
177  0  0  1
178  0  1  0
179  0  1  0
180  0  1  0
181  0  1  0
182  0  1  0
183  0  1  0
184  0  1  0
185  0  1  0
186  0  1  0
187  0  1  0
188  0  1  0
189  0  1  0
190  0  0  1
191  0  0  1
192  0  0  1
193  0  0  1
194  0  0  1
195  0  0  1
196  0  0  1
197  0  0  1
198  0  0  1
199  0  0  1
200  0  0  1

[201 rows x 3 columns]

In [25]:
x_body_style

     0  1  2  3  4
0    1  0  0  0  0
1    1  0  0  0  0
2    0  0  1  0  0
3    0  0  0  1  0
4    0  0  0  1  0
5    0  0  0  1  0
6    0  0  0  1  0
7    0  0  0  0  1
8    0  0  0  1  0
9    0  0  0  1  0
10   0  0  0  1  0
11   0  0  0  1  0
12   0  0  0  1  0
13   0  0  0  1  0
14   0  0  0  1  0
15   0  0  0  1  0
16   0  0  0  1  0
17   0  0  1  0  0
18   0  0  1  0  0
19   0  0  0  1  0
20   0  0  1  0  0
21   0  0  1  0  0
22   0  0  1  0  0
23   0  0  1  0  0
24   0  0  0  1  0
25   0  0  0  1  0
26   0  0  0  1  0
27   0  0  0  0  1
28   0  0  1  0  0
29   0  0  1  0  0
..  .. .. .. .. ..
171  0  0  1  0  0
172  0  0  0  1  0
173  0  0  1  0  0
174  0  0  1  0  0
175  0  0  1  0  0
176  0  0  0  1  0
177  0  0  0  0  1
178  0  0  0  1  0
179  0  0  0  1  0
180  0  0  0  1  0
181  0  0  0  1  0
182  0  0  0  1  0
183  0  0  0  1  0
184  0  0  0  1  0
185  1  0  0  0  0
186  0  0  1  0  0
187  0  0  0  1  0
188  0  0  0  1  0
189  0  0  0  0  1
190  0  0  0  1  0
191  0  0  0  0  1
192  0  0  0  1  0
193  0  0  0  0  1
194  0  0  0  1  0
195  0  0  0  0  1
196  0  0  0  1  0
197  0  0  0  1  0
198  0  0  0  1  0
199  0  0  0  1  0
200  0  0  0  1  0

[201 rows x 5 columns]

In [26]:
X_update = pd.concat([x_update,x_drive_wheels,x_body_style],axis=1)

In [27]:
X_update.head()

,body_style,drive_wheels,engine_location,width,height,curb_weight,engine_size,stroke,peak_rpm,0,1,2,0,1,2,3,4
0,0,2,0,64.1,48.8,2548,130,2.68,5000,0,0,1,1,0,0,0,0
1,0,2,0,64.1,48.8,2548,130,2.68,5000,0,0,1,1,0,0,0,0
2,2,2,0,65.5,52.4,2823,152,3.47,5000,0,0,1,0,0,1,0,0
3,3,1,0,66.2,54.3,2337,109,3.40,5500,0,1,0,0,0,0,1,0
4,3,0,0,66.4,54.3,2824,136,3.40,5500,1,0,0,0,0,0,1,0

In [28]:
X_update = X_update.drop(['body_style','drive_wheels'],axis=1)

In [29]:
X_update.head()

,engine_location,width,height,curb_weight,engine_size,stroke,peak_rpm,0,1,2,0,1,2,3,4
0,0,64.1,48.8,2548,130,2.68,5000,0,0,1,1,0,0,0,0
1,0,64.1,48.8,2548,130,2.68,5000,0,0,1,1,0,0,0,0
2,0,65.5,52.4,2823,152,3.47,5000,0,0,1,0,0,1,0,0
3,0,66.2,54.3,2337,109,3.40,5500,0,1,0,0,0,0,1,0
4,0,66.4,54.3,2824,136,3.40,5500,1,0,0,0,0,0,1,0

In [30]:
x_final = X_update

In [31]:
x_final.columns = ['EL','WID','HT','CWT','ENSZ','STR','PRPM','4WD','FWD','RWD','CV','HAT','HB','SE','WG']

In [32]:
x_final.head()

   EL   WID    HT   CWT  ENSZ   STR  PRPM  4WD  FWD  RWD  CV  HAT  HB  SE  WG
0   0  64.1  48.8  2548   130  2.68  5000    0    0    1   1    0   0   0   0
1   0  64.1  48.8  2548   130  2.68  5000    0    0    1   1    0   0   0   0
2   0  65.5  52.4  2823   152  3.47  5000    0    0    1   0    0   1   0   0
3   0  66.2  54.3  2337   109  3.40  5500    0    1    0   0    0   0   1   0
4   0  66.4  54.3  2824   136  3.40  5500    1    0    0   0    0   0   1   0

In [33]:
x_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 15 columns):
EL      201 non-null int32
WID     201 non-null float64
HT      201 non-null float64
CWT     201 non-null int64
ENSZ    201 non-null int64
STR     201 non-null float64
PRPM    201 non-null int64
4WD     201 non-null uint8
FWD     201 non-null uint8
RWD     201 non-null uint8
CV      201 non-null uint8
HAT     201 non-null uint8
HB      201 non-null uint8
SE      201 non-null uint8
WG      201 non-null uint8
dtypes: float64(3), int32(1), int64(3), uint8(8)
memory usage: 11.9 KB

In [72]:
x_final.corr()[x_final.corr()>abs(0.5)]

,EL,WID,HT,CWT,ENSZ,STR,PRPM,4WD,FWD,RWD,CV,HAT,HB,SE,WG
EL,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WID,NaN,1.000000,NaN,0.866201,0.729436,NaN,NaN,NaN,NaN,0.507028,NaN,NaN,NaN,NaN,NaN
HT,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CWT,NaN,0.866201,NaN,1.000000,0.849072,NaN,NaN,NaN,NaN,0.670611,NaN,NaN,NaN,NaN,NaN
ENSZ,NaN,0.729436,NaN,0.849072,1.000000,NaN,NaN,NaN,NaN,0.559063,NaN,NaN,NaN,NaN,NaN
STR,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRPM,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4WD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FWD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
RWD,NaN,0.507028,NaN,0.670611,0.559063,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN
CV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
HAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
HB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
WG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [73]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
LR = LinearRegression()
RD = Ridge(normalize=True)
LS = Lasso(normalize=True)
EN = ElasticNet(normalize=True)

In [74]:
from sklearn.model_selection import GridSearchCV
param_rd = {'alpha':np.arange(0.01,1,0.01)}
param_ls = {'alpha':np.arange(0.01,1,0.01)}
param_en = {'alpha':np.arange(0.01,1,0.01),'l1_ratio':np.arange(0.01,1,0.01)}

In [78]:
GS_RD = GridSearchCV(RD,param_rd,cv=5,scoring='r2')
GS_RD.fit(x_final,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=True, random_state=None,
                             solver='auto', tol=0.001),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.2...
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='r2', verbose=0)

In [79]:
GS_RD.best_params_

{'alpha': 0.35000000000000003}

In [80]:
GS_LS = GridSearchCV(LS,param_ls,cv=5,scoring='r2')
GS_LS.fit(x_final,y)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 47254678.83171499, tolerance: 1168031.332047205
  positive)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 13595513.7115798, tolerance: 1026505.3408248448
  positive)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 13627165.947974682, tolerance: 1026505.3408248448
  positive)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 13657414.444871426, tolerance: 1026505.3408248448
  positive)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 13686245.588139296, tolerance: 1026505.3408248448
  positive)

GridSearchCV(cv=5, error_score=nan,
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=1000, normalize=True, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0....
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='r2', verbose=0)

In [81]:
GS_LS.best_params_

{'alpha': 0.99}

In [82]:
GS_EN = GridSearchCV(EN,param_en,cv=5,scoring='r2')
GS_EN.fit(x_final,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True,
                                  l1_ratio=0.5, max_iter=1000, normalize=True,
                                  positive=False, precompute=False,
                                  random_state=None, selection='cyclic',
                                  tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12...
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='r2', verbose=0)

In [83]:
GS_EN.best_params_

{'alpha': 0.23, 'l1_ratio': 0.99}

In [84]:
m2 = Ridge(alpha=0.35,normalize=True)
m3 = Lasso(alpha=0.99,normalize=True)
m4 = ElasticNet(alpha=0.23,l1_ratio=0.99,normalize=True)

In [90]:
from sklearn.model_selection import KFold
from sklearn import metrics
kf=KFold(n_splits=5,shuffle=True,random_state=0)
for model,name in zip([LR,m2,m3,m4],['Linear_Regression','Ridge Regression','Lasso Regression','ElasticNet']):
    rmse=[]
    for train_idx,test_idx in kf.split(x_final,y):
        xtrain,xtest=x_final.iloc[train_idx,:],x_final.iloc[test_idx,:]
        ytrain,ytest=y.iloc[train_idx],y.iloc[test_idx]
        model.fit(xtrain,ytrain)
        y_pred=model.predict(xtest)
        mse=metrics.mean_squared_error(ytest,y_pred)
        rmse.append(np.sqrt(mse))
    print('RMSE scores: %0.03f (+/- %0.5f)[%s]' % (np.mean(rmse),np.std(rmse,ddof=1),name))

RMSE scores: 2978.862 (+/- 261.35484)[Linear_Regression]
RMSE scores: 3160.119 (+/- 314.21838)[Ridge Regression]
RMSE scores: 2973.095 (+/- 262.31829)[Lasso Regression]
RMSE scores: 3175.109 (+/- 318.35825)[ElasticNet]

#### NOTE:

###### The drawback of GridSearch is that it only takes Bias Error(RMSE) into account and not the Variance Error.